repos:
- hooks:
  - id: commitizen
  repo: https://github.com/commitizen-tools/commitizen
  rev: master

- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
  - id: fmt
  - id: cargo-check
  - id: clippy
